Repository JuniLearning/eslint-config-juni, pull requests merged in 2020-10, with the labels that each got.

#18 Use @babel/eslint-parser instead of babel-eslint
  package-lock.json
  package.json
  packages/base/index.js
  packages/react/index.js
Labels: size/S

#19 Add .babelrc and two Babel plugins
  .babelrc
  package-lock.json
  package.json
Labels: size/S

#20 React scripts compatibility
  README.md
  package-lock.json
  package.json
  packages/base/rules/styles.js
  packages/react/.eslintrc.js
  packages/react/index.js
  packages/react/rules/jsx-a11y.js
Labels: size/M

#21 Integrate eslint-typescript
  README.md
  package-lock.json
  package.json
  packages/base/rules/styles.js
  packages/react/rules/react.js
  packages/typescript/.eslintrc.js
  packages/typescript/index.js
  packages/typescript/rules/styles.js
Labels: size/M

#22 bump eslint
  package.json
Labels: size/XS
